/* AUTH */
export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const HANDLE_SIGNUP = 'HANDLE_SIGNUP';
export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const SET_USER = 'SET_USER';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_ERR_MESSAGE = 'SET_ERR_MESSAGE';
export const SWITCH_TO_LOGIN = 'SWITCH_TO_LOGIN';
export const SWITCH_TO_SIGNUP = 'SWITCH_TO_SIGNUP';

/* HOME */
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const GET_INPUT_LOCATION = 'GET_INPUT_LOCATION';
export const GET_DISTANCE_MATRIX = 'GET_DISTANCE_MATRIX';
export const GET_CALCULATED_FARE = 'GET_CALCULATED_FARE';
export const GET_CAR_TYPE = 'GET_CAR_TYPE';
export const GET_TOW_TRUCK_TYPE = 'GET_TOW_TRUCK_TYPE';
export const CANCEL_REQUEST = 'CANCEL_REQUEST';
export const GET_NEARBY_DRIVERS = 'GET_NEARBY_DRIVERS';

/* NEW BOOKING */
export const CREATE_BOOKING = 'CREATE_BOOKING';
export const CREATE_TOW_BOOKING = 'CREATE_TOW_BOOKING';
export const UPDATE_TOW_BOOKING = 'UPDATE_TOW_BOOKING';
export const CANCEL_TOW_BOOKING = 'CANCEL_TOW_BOOKING';
export const SET_ACCEPTED_DRIVER = 'SET_ACCEPTED_DRIVER';

/* TOW BOOKINGS */
export const GET_TOW_BOOKING = 'GET_TOW_BOOKING';
export const GET_TOW_BOOKINGS = 'GET_TOW_BOOKINGS';
